### PR TITLE
fix bug: 1x speed skipped

### PR DESCRIPTION
**Pull request by SaneBow**
A fix for issue #252

### CODE REVIEW

**Comment by saagarjha** [comment]
@SaneBow Would you mind explaining in detail what exactly this pull request does? Also, would you mind holding off on this until #165 is merged, since it has a couple changes to the rewind/fast forward mechanism.

**Comment by SaneBow** [comment]
This fix the issue described in #252. In the current code
```swift
   @IBAction func leftButtonAction(_ sender: NSButton) {
      if arrowBtnFunction == .speed {
        let speeds = AppData.availableSpeedValues.count
        // If fast forwarding change speed to 1x
        if speedValueIndex > speeds / 2 {
          speedValueIndex = speeds / 2
        }
        
        if sender.intValue == 0 { // Released
          if maxPressure == 1 { // Single click ended
            speedValueIndex = oldIndex - 1
 ```

The `If fast forwarding change speed to 1x` part of code tried to reset speed to 1x when click on left button (for speed down) while it's playing in fast speed (e.g. 2x). But then the `single click` part again set speed to slower index. So duplicated action happened. This pull request is all about this bug.

Thank you for referring #165, I have checked but it didn't fix this issue.

PS: I think the function of the left button is slow down rather than rewind, maybe someone should fix the typo in comment XD

**Comment by saagarjha** [comment]
This was intended behavior, as that's how QuickTime does it. The left button is intended to be for rewinding, but it's being used to slow down because MPV/IINA currently doesn't support it: https://github.com/lhc70000/iina/blob/master/iina/AppData.swift#L19

**Comment by SaneBow** [comment]
I see. This is a little bit inconvenient in my opinion, but as apple does that, we may better just follow the style.
Thank you for your time. I will close this pull request.

**Pull request closed without merging**
