### PR TITLE
Full Russian localization

### PR DESCRIPTION
**Pull request by euf**
- [x] This change has been discussed with the author.
- [x] It implements Russian translation.

---

**Description:**

This is a result of @imKota's and my efforts combined.
Full and up-to-date Russian translation.

### CODE REVIEW

**Comment by lhc70000** [comment]
Can I close #677?

**Comment by lhc70000** [comment]
Please update the translation for auto load enhancement.

**Localizable.string**
- `pl_menu.matched_sub`
- `pl_menu.add_sub`
- `pl_menu.wrong_sub`

**PlaylistViewController**
- `j2t-mO-cpo.title`
- `zod-Ch-cOH.title`

**PrefSubViewController**
- `xsH-Bm-ZPp.title`
- `ul7-yg-cCb.title`
- `d5R-vH-0o0.title`
- `mVR-wA-nID.title`
- `5eA-EB-Hco.title`
- `VZs-zv-0oM.title`
- `NHu-6z-rEm.title`

**QuickSettingViewController**
- Removed `C97-zJ-O3Y.title`
- Added `AB5-UZ-euc.ibShadowedLabels[0]`
- Added `Rbb-wh-cLc.ibShadowedLabels[0]`

You can search an ID in xib file to locate the UI component.

**Comment by imKota** [comment]
> Can I close #677?

Yeah

**Comment by euf** [comment]
@lhc70000 Translation updated!

**Comment by euf** [comment]
@lhc70000 
First of all, you can close #677. 

Also I wanted to ask if I should try to resolve `iina.xcodeproj/project.pbxproj`conflict or you will do it yourself?

Finally I wanted you to have a look at some UI problems, which came out while testing Russian translation — see issue #692.

**Comment by alejx** [comment]
@euf I have helped you to resolve the conflicts. You can continue your work now.

**Comment by euf** [comment]
@alejx Thank you! Still had to so it again, develop branch is so active 😎 
You can mark this PR with the `progress: PR ready` label, since all the work is done here. The only reason for me to commit something else now is to fix a typo or change some word for a synonym.

**Pull request merged**
