### PR TITLE
Fix some autolayout problems

### PR DESCRIPTION
**Pull request by skyline75489**
- [ ] This change has been discussed with the author.
- [X] It implements / fixes issue parts of #692 .

---

**Description:**

This fixes spacing problems 3,5,6.

### CODE REVIEW

**Comment by skyline75489** [comment]
This indeed breaks old layouts in the perspective of design. I'm not really sure how to balance all those things.

**Comment by vit9696** [comment]
@skyline75489 could you please check whether this works fine with `Show scroll bars` preference set to always? There are the discussions in #588 and https://github.com/lhc70000/iina/issues/486#issuecomment-286824692. Thanks.

**Comment by skyline75489** [comment]
@vit9696 I check with `Show scroll bars`. Seems to work fine.

**Comment by alejx** [comment]
Close since #692 has marked as fixed.

**Pull request closed without merging**
