### PR TITLE
Updated Japanese localization

### PR DESCRIPTION
**Pull request by LEoREo2247**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

I have updated/filled all missing Japanese localizations for 1.0.0-beta4.
I still haven't tested in live yet as I'm failing to build the project on my earlier beta version of Xcode, but I'm pretty sure it works and I will going to test with newer Xcode beta very soon.

### CODE REVIEW

**Comment by alejx** [comment]
Four ja string files for xibs are missing.
```
PrefUtilsViewController.strings
OpenURLWindowController.strings
PreferenceWindowController.strings
SubChooseViewController.strings
```
Feel free to ask me questions if you don't know how to manipulate them.
Other parts look good to me. Great work and clean diff!

**Comment by LEoREo2247** [comment]
Oh, I didn't noticed for the files that still haven't created.
Will also going to add that very shortly!

**Comment by LEoREo2247** [comment]
Okay so I have added other missing string files too.

**Comment by alejx** [comment]
Everything works smoothly. But unfortunately, since we have already released beta 4, your work will be included in this beta release. It will surely in our next beta release. Thank you!

Ref: #1947

**Pull request merged**
