### PR TITLE
Add argument for stdin piping to iina-cli help

### PR DESCRIPTION
**Pull request by snipem**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

The piping capability was only described but the actual arguments where not shown. I only found out about this by looking at the code.

### CODE REVIEW

**Comment by lhc70000** [comment]
No, you don't need to add `--stdin` to pipe. Try something like `cat /path/to/file | iina` and it should work.

**Comment by snipem** [comment]
@lhc70000 I'm afraid it does only work when using the `--stdin` argument:

```
~  $ iina --help
IINA 0.0.15 Build 68
This binary is not intended for being used as a command line tool. Please use the bundled iina-cli.
Please ignore this message if you are running in a debug environment.
^C
~  $ curl --silent http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 | iina-cli
^C
~  $ curl --silent http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 | iina-cli --stdin
```

The second to last command does nothing besides opening the IINA file chooser. The last command with the `--stdin` argument does play the video piped over curl.

**Comment by snipem** [comment]
I read through your response and saw that you mentioned `iina` instead of `iina-cli`. The result is the same:

```
~  $ curl --silent http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 | iina  
^C
```

Only the IINA file chooser is opening.

**Comment by ErikMinekus** [comment]
```cat /path/to/file | iina-cli``` works with a 12MB MP3 file, but not with a 15MB MP3 file. So it seems that if the file is larger than some unknown buffer size, or if the file size is unknown, the file is not fully passed to IINA.

**Comment by lhc70000** [comment]
@snipem IINA cannot detect whether stdin has data when you pipe from an online resource, so yes, this is where `--stdin` should be used (and I forgot it). 

Could you update the help message accordingly?

**Pull request merged**
