### PR TITLE
Synchronize QuickSettingsView text fields and slider and localize, fix #425, #492

### LINKED ISSUE #425: Play speed input validation
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.5

**Expected behavior:**

User wants to adjust custom play speed. In Edit field is already written "1.00" so user expect to write "1.33" and that value to be accepted and applied.

**Actual behavior:**

If user tries to write "1.33" or any other decimal value using decimal point (".") it doesn't work. It is necessary to write value using comma "," like "1,33" value to be accepted, despite default value displayed with decimal point. Any future value will be displayed with decimal point as well but newly written value need to be entered using comma instead of point.

Crash report:
There is no crash.

**Steps to reproduce:**
Already described in expected/actual behaviour

**How often does this happen?**
Always

### PR DESCRIPTION
**Pull request by saagarjha**
- [ ] This change has been discussed with the author.
- [X] It implements / fixes issue #425, #495

---

**Description:**
Fixes issue #425, #495.

### CODE REVIEW

**Comment by lhc70000** [comment]
Do other text fields have the same potential problem?

**Comment by saagarjha** [comment]
It appears that the audio delay and subtitle delay text fields should have the same issue. Would you like me to add those to this pull request?

**Comment by lhc70000** [comment]
Please add them, thanks.

**Comment by saagarjha** [comment]
@lhc70000 Added the other text fields.

**Comment by lhc70000** [comment]
- If enter a value lower than min value like 0.20, the indicator will only display "0.25" without "x"
- Indicator's position is incorrect: the first tick is not aligned with the left frame border, and the same with the last tick.
1df5f7d2-ab00-4f46-8efb-aee41b7e19cd


I'll fix them later after merged.

**Comment by lhc70000** [comment]
See cdf5b7f.

Also, please don't clamp values from textfields. They're designed for inputting values that the slider can't represent.

**Comment by saagarjha** [comment]
@lhc70000 I pretty sure we don't want a negative speed…

**Pull request merged**
