### PR TITLE
Russian localization for 1.0.0

### PR DESCRIPTION
**Pull request by imKota**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

### CODE REVIEW

**Comment by alejx** [comment]
Ref: #2054

**Comment by alejx** [comment]
In Localizable.strings, alert.config.cannot_create has a placeholder %@, which should also appear in the corresponding translation. Please fix it.

**Comment by imKota** [comment]
@alejx done ;)

**Comment by alejx** [comment]
Thanks!

**Pull request merged**
