### PR TITLE
updated french translation for 0.0.13

### PR DESCRIPTION
**Pull request by superzazu**
Result of check_translation.swift:
```
$ ./other/check_translation.swift fr
---
# AboutWindowController.xib #
---
# Contribution.rtf #
---
# CropSettingsViewController.xib #
---
# FilterPresets.strings #
---
# FilterWindowController.xib #
---
# FontPickerWindowController.xib #
---
# FreeSelectingViewController.xib #
---
# HistoryWindowController.xib #
---
# InfoPlist.strings #
  [x] Cannot read file "./iina/Base.lproj/InfoPlist.strings"
---
# InitialWindowController.xib #
---
# InspectorWindowController.xib #
---
# KeyBinding.strings #
---
# KeyRecordViewController.xib #
---
# Localizable.strings #
---
# MainMenu.xib #
---
# MainWindowController.xib #
---
# OpenURLAccessoryViewController.xib #
---
# PlaylistViewController.xib #
---
# PrefAdvancedViewController.xib #
---
# PrefCodecViewController.xib #
---
# PrefControlViewController.xib #
---
# PrefGeneralViewController.xib #
---
# PrefKeyBindingViewController.xib #
---
# PrefNetworkViewController.xib #
---
# PrefSubViewController.xib #
---
# PrefUIViewController.xib #
---
# QuickSettingViewController.xib #
---
# SubSelectWindowController.xib #

Finished. Issues count:
fr 0
```

### CODE REVIEW

**Comment by alejx** [comment]
Thanks for your work!

The translation of `subencoding.auto` in `Localizable.strings (French)` is missing.

**Comment by superzazu** [comment]
Ah, sorry about this. I don't currently have my computer on me; so it might take me a couple of days to fix this.

**Comment by superzazu** [comment]
Just added the missing translation.

**Comment by alejx** [comment]
@superzazu No need to do that, I can always squash and merge.

**Pull request merged**
