### PR TITLE
Solve a minor issue at QuickSettingViewController.xib

### PR DESCRIPTION
**Pull request by MuntashirAkon**
- [x] This change has been discussed with the author (who told me to explain it further).
- [x] Fixed the width and arrangement of the custom field for `Aspect Ratio`
- [x] Fixed the arrangement of the `Custom...` button of `Crop`

---

**Description:**
For the sake of clarity, let's look at the changes by comparing two images:
Before:
screen shot 2017-09-07 at 2 01 48 am
After:
screen shot 2017-09-07 at 2 02 35 am

(Screenshots were taken on macOS 10.13. First shot was from iina v0.0.12 build 37 and the later was the result after the compilation)

### CODE REVIEW

**Comment by MuntashirAkon** [comment]
As you said earlier, merge only the [`56cc613`](https://github.com/lhc70000/iina/pull/1016/commits/56cc613fe5447f39a8f1f4cc49876ed0368ca61d).

**Comment by lhc70000** [comment]
I'm still not sure if this is the best solution - we should always avoid cropping text.

How about adding a wrapping scroll view for the segment control?

**Comment by MuntashirAkon** [comment]
Would this do any justice to the UI? I think it will look even worse.

**Comment by MuntashirAkon** [comment]
I've reverted the change and closing this. Maybe I can do better :)

**Pull request closed without merging**
