### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by sevenfourk**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

@lhc70000, firstly, thanks for IINA. I wanted something like QuickTime/mpv hybrid on my Mac. UI is important indeed, thought functionality goes right along too.

Added Ukrainian translation.  Ran check translation script.  Was showing 0 issues. But got this one only:

```
# InfoPlist.strings #
  [x] Cannot read file "./iina/Base.lproj/InfoPlist.strings"
```

### CODE REVIEW

**Comment by lhc70000** [comment]
Great job and thanks a lot! I'll review it tomorrow.

**Comment by lhc70000** [comment]
Everything is perfect except some `read.` keys in `KeyBinding.strings`.

For example, in

```
"read.seek" = "Пропустити {{#fwd}}forward{{/fwd}}{{#bwd}}backward{{/bwd}}{{#abs}}до{{/abs}} {{value}}{{#sec}}с{{/sec}}{{#per}}%{{/per}} {{#exact}}(exact){{/exact}}{{#kf}}(keyframe){{/kf}}";
```

"forward", "backward", etc. should be in your language.

**Comment by sevenfourk** [comment]
@lhc70000, thanks, pushed fix for your review. I see that in other languages these two strings: "read.seek", "read.sub-seek" not fully translated, like in my version.

**Comment by lhc70000** [comment]
@sevenfourk Thanks, I'll check them later.

**Pull request merged**
