### PR TITLE
Add Korean Translation

### PR DESCRIPTION
**Pull request by darkbrow**
Add Korean Translation

### CODE REVIEW

**Comment by lhc70000** [comment]
Thanks a lot! 

May I ask if you are Jinbong Kim who emailed me yesterday?

**Comment by darkbrow** [comment]
Yes. It was me.

**Comment by lhc70000** [comment]
Thanks again for your work.

There're just some minor issues:

- Please change base branch do `develop`.
- In `Localizable.strings`, please change the `%@` in `"main.buffering_indicator"`(line 5) to `%d` (it's a bug). So the result should be like:
   ```js
   "main.buffering_indicator" = "준비중… %d%%";
   ```

**Comment by darkbrow** [comment]
Just submitted this request to develop branch.
So I close this pull request.

**Comment by saagarjha** [comment]
@darkbrow Just FYI, Github lets you change the branch you're merging into now. You can find it under the pull request title.

**Pull request closed without merging**
