### PR TITLE
Update Trad. Chinese translations

### PR DESCRIPTION
**Pull request by LEOYoon-Tsaw**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

### CODE REVIEW

**Comment by LEOYoon-Tsaw** [comment]
@saagarjha I don't know how, I'll need some time.

**Comment by saagarjha** [comment]
If you're having trouble, try this out:

1. Run `git rebase -i HEAD~5`. This will open a text editor.
2. Find the lines with "Merge remote-tracking branch 'lhc70000/develop' into develop". Change the "pick" in those lines to "squash".
3. Save and quit the editor.
4. Run `git push --force`.

**Comment by LEOYoon-Tsaw** [comment]
I still have no idea what to do to remove the "merge" commit. By running "git rebase -i HEAD~5" I find no line of "Merge remote-tracking branch 'lhc70000/develop' into develop", and I reverted the commits and recommited.

**Comment by alejx** [comment]
I'm afraid you are completely wrong now. Do you know the usage of `git cherrypick`? In order to not make the problem messier, you'd better use cherrypick to make a new branch fork from the latest develop and keep your work.

**Comment by saagarjha** [comment]
@alejx `git reset --hard 963ce9d` should at least revert it to how it originally was, right?

**Comment by alejx** [comment]
It should be, but I think to make a new branch is the better way.

**Comment by lhc70000** [comment]
Any progress / need any help?

**Comment by alejx** [comment]
@LEOYoon-Tsaw Can I close this pr? It seems like this is abandoned.

**Pull request closed without merging**
