### PR TITLE
Separate Logger from Utility

### PR DESCRIPTION
**Pull request by skyline75489**

### CODE REVIEW

**Comment by skyline75489** [comment]
Should I PR to develop instead?

**Comment by lhc70000** [comment]
Please read [CONTRIBUTING.md](https://github.com/lhc70000/iina/blob/master/CONTRIBUTING.md) first. **Before actually starting doing something, please open an issue (or at least discuss with us in other ways).**

There will be a refactor sooner or later for not only the logging part; and maybe we'll consider using another logging framework. Additionally, as IINA is still in alpha, I prefer logging to system for debug propose now.

Thanks for your effort but I'm so sorry that this is not something we planning to do currently. Welcome contributing when IINA is stable (should be in few weeks) and after a discussion. If you have any consideration, please kindly leave a reply.

**Comment by skyline75489** [comment]
I'd suggest to put 

>Please read CONTRIBUTING.md first. 

in `README.md`. You know. Most people like me will just read the first 200 lines of `README.md` before forking and sending PRs.

Thanks for the reply and this project. Cheers 🍺

**Comment by lhc70000** [comment]
感谢理解 m(_ _)m

**Comment by skyline75489** [comment]
It'd be nice if there is some kind of roadmap we can see so that we can know where this project is heading.

By the way, the `help wanted` label of issues actually means that this issue is open for outsiders to contribute. It helps people to find the issues they can work on.

楼主标的那些 `help wanted` 其实应该标成 `question` 比较合适。不然这两个意思不就重复了吗...

**Comment by lhc70000** [comment]
Thanks for pointing out!

**Pull request closed without merging**
