### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by shorshe**
translated all missing strings with the translation utility

### CODE REVIEW

**Comment by fabi94music** [comment]
Did you consider #1427 ? The „keine“ instead of „leer“ audio or subtitle track selection.

**Comment by shorshe** [comment]
Just go for it. I‘m fine with anyone improving the German translation.

**Comment by fabi94music** [comment]
Problem is I just don't know how to do it yet :P

**Comment by sgoehre** [comment]
Damn, and I just finished the translation as well when I found this commit. :D 

Anyway, since you seem to have changed more files than I, some suggestions to your translation, @shorshe :

1) We should either use "Website" or the German "Webseite". I know @J-rg and I used "Webseite" before, you use "Website". We should agree on one or the other. :-)

2) Do we use "AN/AUS" or "umschalten" for "toggle"? I used "umschalten" before and was going to use it again now. Same issue as before, we should agree on one. (used by you in _Localizable.strings_ → alert.assrt_token_prompt.message)

3) Strings:

**InitialWindowController.strings**
s3U-4u-gYp → "Want to rollback?" ist nicht "Änderungen verwerfen?". Hier geht es mMn darum, auf eine stabile Version zurückzukehren. Ich habe es mit "Du willst auf eine stabile Version zurück?" übersetzt.

3aN-Hg-GkT→ "offizielle Webseite" wird klein geschrieben. Nur als Überschrift oder Eigenname groß.

BIz-NQ-0qD → "E-Mail ... oder **eine** GitHub **I**ssue"

**PrefUIViewController.strings**
fZh-cN-8FM.title → "On Screen Controller" wurde im selben Dialog mit "Steuerelemente" übersetzt. Sollten eins von beidem verwenden.

@fabi94music Read this: https://github.com/lhc70000/iina/wiki/Translation#3-check-your-translation-automatically just managed to do this for the first time today as well. ;-) Before, I just sent the translated files to colliderli.

**Comment by shorshe** [comment]
Sorry to preempt your work. Did not know you were on it.

Changing Website to Webseite right now in my commit.

I do not agree with umschalten instead of AN/AUS. In my opinion AN/AUS is much clearer, since there is no apt single word translation for toggle. I’d vote to use AN/AUS instead of umschalten.

You are totally right on the rest of the corrections i’m working them in right now.

**Comment by shorshe** [comment]
> No worries. Your translations seem a bit better than mine anyway. ;-)

Thanks :)

>  However, I, too, think that „umschalten“ sounds a bit weird and never really cared for it. Just wanted us to be on the same page. :-)

How about ein-/ausschalten ?

**Comment by sgoehre** [comment]
Sounds good to me. I’ll see if I can change all older instances of „umschalten“ in the translation to „ein-/ausschalten“. Have to fix some other minor things I and others discovered anyway. But after your PR went through. ;)

**Comment by shorshe** [comment]
OK, done.

@lhc70000

**Comment by fabi94music** [comment]
If you agree on the use of „keine“ instead of „leer“ Audiospur could you please change that as you are already changing the file ? Thanks :)

**Comment by ErikMinekus** [comment]
@shorshe in InitialWindowController.strings: ```Du kannst uns über<a href``` there should be a space between über and <a href.

**Comment by alejx** [comment]
A quick look at this branch, two files are missing currently. `FilterPresets.strings (German)` (under `Models` folder in Xcode), and `PrefOSCToolbarSettingsSheetController.xib` (this is a new file, under `Preference` folder in Xcode).

**Comment by shorshe** [comment]
I used the translation utility and translated every string that showed up as missing. 

Are these files not imported?

**Comment by alejx** [comment]
@shorshe That's probably the issue, I will find out once your discussion is finished.

**Comment by alejx** [comment]
@shorshe The translation utility does not prompt you when there's a new file that need to translate for now. So that you have to manually create that file and add it into Xcode.

This small panel is newly added into IINA.
screen shot 2018-03-26 at 4 47 20 pm
And the other one, I believe, is this panel:
screen shot 2018-03-26 at 5 14 38 pm

**Comment by shorshe** [comment]
Ok, found them. I'm on it.

**Comment by shorshe** [comment]
@fabi94music tried to find where leer is used... couldn't find the corresponding file. Any hints anyone?

**Comment by fabi94music** [comment]
Think it’s in the localizable.strings und „track.none“

**Comment by shorshe** [comment]
Thanks @fabi94music. Done.

**Comment by alejx** [comment]
@sgoehre It seems you accidentally changed a da localization file, please revert that back before I can merge this PR in.

**Comment by shorshe** [comment]
@alejx don't blame @sgoehre ... it was me ;)

**Pull request merged**
