### PR TITLE
[Japanese] added new strings for 0.0.12

### PR DESCRIPTION
**Pull request by matsune**
- [x] This change has been discussed with the author.
- [x] It implements / fixes issue #826 .

### CODE REVIEW

**Comment by alejx** [comment]
Thanks for your work!
I ran the script checker, it gave me: 
```
  [!][ja] Key "VZs-zv-0oM.title" doesn't exist in PrefSubViewController
  [!][ja] Key "xsH-Bm-ZPp.title" doesn't exist in PrefSubViewController
  [!][ja] Key "5eA-EB-Hco.title" doesn't exist in PrefSubViewController
  [!][ja] Key "d5R-vH-0o0.title" doesn't exist in PrefSubViewController
  [!][ja] Key "NHu-6z-rEm.title" doesn't exist in PrefSubViewController
  [!][ja] Key "mVR-wA-nID.title" doesn't exist in PrefSubViewController
  [!][ja] Key "ul7-yg-cCb.title" doesn't exist in PrefSubViewController
```
and
```
  [!][ja] Key "j2t-mO-cpo.title" doesn't exist in PlaylistViewController
  [!][ja] Key "zod-Ch-cOH.title" doesn't exist in PlaylistViewController
```
Please add these strings.

**Comment by alejx** [comment]
Thanks for your work!
I ran the script checker, it gave me: 
```
  [!][ja] Key "VZs-zv-0oM.title" doesn't exist in PrefSubViewController
  [!][ja] Key "xsH-Bm-ZPp.title" doesn't exist in PrefSubViewController
  [!][ja] Key "5eA-EB-Hco.title" doesn't exist in PrefSubViewController
  [!][ja] Key "d5R-vH-0o0.title" doesn't exist in PrefSubViewController
  [!][ja] Key "NHu-6z-rEm.title" doesn't exist in PrefSubViewController
  [!][ja] Key "mVR-wA-nID.title" doesn't exist in PrefSubViewController
  [!][ja] Key "ul7-yg-cCb.title" doesn't exist in PrefSubViewController
```
and
```
  [!][ja] Key "j2t-mO-cpo.title" doesn't exist in PlaylistViewController
  [!][ja] Key "zod-Ch-cOH.title" doesn't exist in PlaylistViewController
```
Please add these strings.

**Comment by matsune** [comment]
@alejx Thank you for checking! I didn't know such a nice script.
I added missing strings so please recheck!

**Comment by alejx** [comment]
Merged just now. However, I notice that you did not translate "Italic" and "Bold". Does it a convention? If not, please add them in your next PR. Thanks!

**Pull request merged**
