### PR TITLE
Monospaced font for time labels in OSC and Touch Bar

### PR DESCRIPTION
**Pull request by ErikMinekus**
- [ ] This change has been discussed with the author.
- [x] It implements / fixes issue #1377.

---

**Description:**
I couldn't find a constant for the System Mini font size (9pt) for the mini player, so it's hardcoded.

### CODE REVIEW

**Comment by saagarjha** [comment]
I could have sworn we've had other pull requests to this effect…

**Comment by ErikMinekus** [comment]
#862 was closed by the author and never merged. I can put the code in ```DurationDisplayTextField``` if you can tell me which function to use. It didn't work for me in the init function.

**Comment by ErikMinekus** [comment]
I tried
```swift
override var font: NSFont? = .monospacedDigitSystemFont(ofSize: font!.pointSize, weight: .regular)
```
but it returned these errors:
- Cannot override with a stored property 'font'
- Variable used within its own initial value

I did however just find ```viewWillDraw```:
```swift
  override func viewWillDraw() {
    if #available(OSX 10.11, *), let currentFont = font {
      font = .monospacedDigitSystemFont(ofSize: currentFont.pointSize, weight: .regular)
    }
  }
```
Which works great for the main window and mini player, but not for the Touch Bar. That's because the font property returns the system font (San Francisco UI size 13), but the actual font used in the Touch Bar is San Francisco Condensed size 15.

**Comment by saagarjha** [comment]
You need to override it with a computed property:

```swift
override var font: NSFont? {
	get {
		return .monospacedDigitSystemFont(ofSize: 0, weight: .regular)
	}
	set {
	}
}
```

**Comment by ErikMinekus** [comment]
Thanks, that works for the UI. The Touch Bar still renders the text at size 13 though, instead of size 15. Even though it works fine when I remove the font override and use the same code in the ```TouchBarSupport``` class:
```swift
label.font = .monospacedDigitSystemFont(ofSize: 0, weight: .regular)
```

**Comment by ErikMinekus** [comment]
That code compiles, but it still uses the font set in Interface Builder, without monospacing.

**Comment by alejx** [comment]
@saagarjha Is there any benefit to override `font` in `DurationDisplayTextField`? Though `DurationDisplayTextField`s have same font, they have different font size. So that we have to set their size separately.

**Comment by ErikMinekus** [comment]
@alejx I imagine the benefit is to get the font size that's set in Interface Builder, instead of hardcoding it like I have done now. But so far overriding the font in ```DurationDisplayTextField``` seems to actually cause issues with the different font sizes.

**Comment by saagarjha** [comment]
> That code compiles, but it still uses the font set in Interface Builder, without monospacing. It also doesn't solve the font size issue in the Touch Bar.

Yeah, now that I think about it that won't work. I think your solution is OK.

> That's because the font property returns the system font (San Francisco UI size 13), but the actual font used in the Touch Bar is San Francisco Condensed size 15.

Wait, what? How are you checking this?

**Comment by ErikMinekus** [comment]
It's mentioned in the Advanced Touch Bar session from WWDC 2017: https://developer.apple.com/videos/play/wwdc2017/222/?time=2416

After that they explain using the system font of size 0 to get the right font, and how to set the monospaced font.

**Comment by alejx** [comment]
@saagarjha Can I merge this in?

**Pull request merged**
