### PR TITLE
Improved syntax

### PR DESCRIPTION
**Pull request by sn0wyfall**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

### CODE REVIEW

**Comment by alejx** [comment]
Please change your base branch to develop to avoid extra work. Thanks.

**Comment by sn0wyfall** [comment]
@alejx I really have no clue how to do that. Could you give me a quick pointer?

**Comment by alejx** [comment]
@sn0wyfall Press `Edit` at the right of the title, and choose the correct base branch.

**Comment by sn0wyfall** [comment]
@alejx Oh wow that was easy. Thanks!

**Pull request closed without merging**
