### PR TITLE
Add Safari app extension

### PR DESCRIPTION
**Pull request by saagarjha**
- [X] This change has been discussed with the author.
- [X] It implements / fixes issue #1988.

---

Converts the old Safari JavaScript extension into an app extension.

Currently, it still needs some work:
* We need a new toolbar icon. Please replace the icon with an appropriate PDF image.
* Right clicking on links doesn't quite work, for a variety of reasons. We can discuss how we want to move forward with this here.
* This can only be installed if the *entire app bundle*, including the extension, is properly signed. Ad-hoc signatures will cause it to be rejected by Safari.

### CODE REVIEW

**Comment by lhc70000** [comment]
> Right clicking on links doesn't quite work, for a variety of reasons. We can discuss how we want to move forward with this here.

Could you elaborate more on the exact reasons? I just tested roughly and seems that each time a new `SafariExtensionHandler` is created dynamically so there's no way to store the URL received in `messageReceived` inside the handler class, but if I store it outside the class, like in a `fileprivate var`, it works.

**Comment by saagarjha** [comment]
Wait, hold on: context menus can define a custom `userInfo` dictionary. Ignore what I said before.

I think the only thing this needs now is an icon file and it should be good to go–unless you see anything wrong with it?

**Comment by jimblue** [comment]
Hey!

Seems to be merged but I don't see iina extensino in the appstore...

Did I miss something?

**Comment by inflation** [comment]
@jimblue You don’t need to manually install the extension. Once you have the next version installed, Safari would load it automatically. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saagarjha** [comment]
You may actually have to run IINA before it shows up, just FYI. Then you should be able to enable it from Safari's preferences.

**Comment by jimblue** [comment]
@inflation @saagarjha, thanks, but what do you mean by the next version installed?
I'm actually running iina 1.0.0-beta4 (92)

**Comment by inflation** [comment]
@jimblue We would be rolling out the official 1.0 in the following weeks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jimblue** [comment]
oh ok that's great! thank you so much guys, I love iina ❤️ !!!

**Comment by pimvanriezen** [comment]
Just wanted to point out that it is in no way obvious that the extension is automatically added to Safari. I spent some time today trying to download and activate the old safariextz, and searching through the Safari extension gallery, before I figured out it was already added to my extensions, but disabled.

**Comment by saagarjha** [comment]
Agree that it should be made more explicit to users how to “install” the extension. I feel like this falls under the work I outlined in #1988.

**Comment by LEoREo2247** [comment]
I updated IINA to 1.0.0 through in-app updater, however the new extension was not added to Safari and I had to download then re-install it from github's release page in order to make it appear in Safari.

New extension should have bundled in app even if it's updated through updater. I wonder if there is any function to let or force Safari to re-detect bundled extensions so that we can run that on first-launch after next update. If that is possible, then we can also re-add Safari button at preferences so users can manually do that.

**Pull request merged**
