### PR TITLE
spanish translation for 0.0.15

### PR DESCRIPTION
**Pull request by Aikyuichi**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**

### CODE REVIEW

**Comment by alejx** [comment]
I noticed that the Spanish localization has many untranslated strings. You should use `iina/others/check_translation.swift es` to find them; or simply use [iina-translation-utility](https://github.com/iina/iina-translation-utility), it will prompt you untranslated or invalid strings.

**Comment by Aikyuichi** [comment]
@alejx 
it is necessary to translate strings like: Label, Text Cell, Box, Table View Cell?

**Comment by alejx** [comment]
They are not necessary to be translated.

**Comment by alejx** [comment]
There are still two files to be translated: `FreeSelectingViewController.strings` and `FilterPresets.strings`.

**Pull request merged**
