### PR TITLE
remove border for file path field in inspect window

### PR DESCRIPTION
**Pull request by phill84**
Inspect window is now made unresizable, and the border around file path text field is removed.
Also the end of file path will be truncated with ellipsis if it is too long.

### CODE REVIEW

**Comment by megadr01d** [comment]
@phill84 Just curious, why unresizable?

**Comment by alejx** [comment]
@megadr01d Cause textfields and many other components in the inspect window cannot been resized currently.

**Comment by phill84** [comment]
Exactly, nothing gets auto-resized currently when you change the window size.

**Comment by saagarjha** [comment]
On it!

**Comment by lhc70000** [comment]
**PLEASE READ [CONTRIBUTING.md](https://github.com/lhc70000/iina/blob/master/CONTRIBUTING.md) FIRST.**

> Please open an issue before actually starting doing something to make sure that there's not someone else working on the same feature.

Especially when it's UI related. IINA is now in rapid development, which means there will be a brunch of stuff to be added or removed. We need to have a **discussion** before you starting working to make sure there's no conflict with our plan. If I didn't make it clear in CONTRIBUTING.md, sorry for that and I'll update it on next release.

---

For inspector, it's even not working fully. According to existing feature requests and plan, we are going to redesign the layout (maybe use a tab view) to add more information (subtitles info, mpv status, etc.) and current one will possibly be completely replaced. So it makes no sense to improve current layout (and that's why I didn't add AutoLayout for inspector only).

The reason why file path field is boarded is that I want to let user know they can select and copy it. 

@saagarjha Please keep only one topic for each PR. See CONTRIBUTING.md:

> Please submit separate pull requests for different features.

**Comment by phill84** [comment]
@lhc70000 thanks for the clarification. However I would say that changing of cursor is an indicator clear enough for the users.

**Comment by saagarjha** [comment]
Heh heh, I have a tendency to add a bunch of things to my pull requests. I'll revert them.

**Pull request closed without merging**
